name: Create Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from PR title or commit
        id: get_version
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ $PR_TITLE =~ v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            VERSION=$(echo $PR_TITLE | grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+')
          else
            # デフォルトバージョン取得ロジック（パッケージJSONなどから）
            VERSION=$(grep -o '"version": "[^"]*"' package.json | cut -d'"' -f4)
            VERSION="v$VERSION"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: ${{ steps.get_version.outputs.version }}
          body: |
            ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false