name: Release to Chrome Web Store

on:
  workflow_run:
    workflows: ["Test Coverage"]
    types:
      - completed
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request'

    steps:
      - name: Download extension artifact
        uses: actions/download-artifact@v4
        with:
          name: extension-package

      - name: Submit to Chrome Web Store
        run: |
          npx chrome-webstore-upload-cli@2 upload --source extension.zip --auto-publish
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}